name: Deployment pipeline

on:
    push:
        branches:
            - pipeline_tests
    # pull_request:
    #     branches: [main]
    #     types: [opened, synchronize]
jobs:
    simple_deployment_pipeline:
        name: Deploy app
        # Optional only deploy if it is a pull request approved
        if: ${{ github.event_name == 'push' && !contains( join(github.event.commits.*.message), '#skip')}}
        runs-on: ubuntu-24.04
        concurrency: deploy-group # optional: ensure only one action runs at a time
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            # - uses: superfly/flyctl-actions/setup-flyctl@master
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
            - run: pwd && ls -ltr
            - name: Install Frontend Dependencies
              run: cd client && npm ci
            - run: pwd && ls -ltr
            - name: Lint Frontend
              run: npm run lint
            - name: Build Frontend
              run: npm run build
            - name: Pack Frontend into the Backend
              run: cd ../server/ && rm -rf dist && cp -r ../client/dist/ dist
            - name: Install Backend Dependencies
              run: npm ci
            - name: Lint Backend
              run: npm run lint
            - name: Test Backend
              run: npm run test
            - name: Preparing to run e2e tests
              run: cd ../client/
            - name: Install Playwright Browsers
              run: npx playwright install --with-deps
            - name: e2e tests
              run: npx playwright test
            # - uses: actions/upload-artifact@v4
            #   if: ${{ !cancelled() }}
            #   with:
            #       name: playwright-report
            #       path: playwright-report/
            #       retention-days: 30
            # - run: flyctl deploy --remote-only
            #   env:
            #       FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
